/**
 * 错误码常量
 */

/**
 * 通用错误码
 */
export const ERROR_CODES = {
  // 成功
  SUCCESS: 0,

  // 通用错误
  UNKNOWN_ERROR: -1,
  INVALID_PARAMETER: 1001,
  MISSING_PARAMETER: 1002,
  INVALID_FORMAT: 1003,
  INVALID_TYPE: 1004,
  INVALID_VALUE: 1005,
  OUT_OF_RANGE: 1006,
  EMPTY_RESULT: 1007,

  // 权限错误
  UNAUTHORIZED: 2001,
  FORBIDDEN: 2002,
  TOKEN_EXPIRED: 2003,
  TOKEN_INVALID: 2004,
  INSUFFICIENT_PERMISSIONS: 2005,

  // 资源错误
  RESOURCE_NOT_FOUND: 3001,
  RESOURCE_ALREADY_EXISTS: 3002,
  RESOURCE_DELETED: 3003,
  RESOURCE_LOCKED: 3004,
  RESOURCE_LIMIT_EXCEEDED: 3005,

  // 业务逻辑错误
  BUSINESS_LOGIC_ERROR: 4001,
  OPERATION_NOT_ALLOWED: 4002,
  STATE_CONFLICT: 4003,
  DEPENDENCY_ERROR: 4004,
  VALIDATION_ERROR: 4005,

  // 系统错误
  SYSTEM_ERROR: 5001,
  DATABASE_ERROR: 5002,
  NETWORK_ERROR: 5003,
  TIMEOUT_ERROR: 5004,
  CONFIGURATION_ERROR: 5005,

  // 外部服务错误
  EXTERNAL_SERVICE_ERROR: 6001,
  EXTERNAL_SERVICE_UNAVAILABLE: 6002,
  EXTERNAL_SERVICE_TIMEOUT: 6003,
} as const;

/**
 * 错误级别
 */
export const ERROR_LEVELS = {
  DEBUG: 'debug',
  INFO: 'info',
  WARNING: 'warning',
  ERROR: 'error',
  CRITICAL: 'critical',
} as const;

/**
 * 错误类型
 */
export const ERROR_TYPES = {
  VALIDATION: 'validation',
  AUTHENTICATION: 'authentication',
  AUTHORIZATION: 'authorization',
  NOT_FOUND: 'not_found',
  CONFLICT: 'conflict',
  RATE_LIMIT: 'rate_limit',
  INTERNAL_SERVER: 'internal_server',
  BAD_GATEWAY: 'bad_gateway',
  SERVICE_UNAVAILABLE: 'service_unavailable',
  TIMEOUT: 'timeout',
} as const;

/**
 * 错误消息模板
 */
export const ERROR_MESSAGES = {
  [ERROR_CODES.SUCCESS]: '操作成功',
  [ERROR_CODES.UNKNOWN_ERROR]: '未知错误',
  [ERROR_CODES.INVALID_PARAMETER]: '参数无效',
  [ERROR_CODES.MISSING_PARAMETER]: '缺少必要参数',
  [ERROR_CODES.INVALID_FORMAT]: '格式无效',
  [ERROR_CODES.INVALID_TYPE]: '类型无效',
  [ERROR_CODES.INVALID_VALUE]: '值无效',
  [ERROR_CODES.OUT_OF_RANGE]: '值超出范围',
  [ERROR_CODES.EMPTY_RESULT]: '结果为空',
  [ERROR_CODES.UNAUTHORIZED]: '未授权访问',
  [ERROR_CODES.FORBIDDEN]: '禁止访问',
  [ERROR_CODES.TOKEN_EXPIRED]: '令牌已过期',
  [ERROR_CODES.TOKEN_INVALID]: '令牌无效',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: '权限不足',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: '资源不存在',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: '资源已存在',
  [ERROR_CODES.RESOURCE_DELETED]: '资源已删除',
  [ERROR_CODES.RESOURCE_LOCKED]: '资源已锁定',
  [ERROR_CODES.RESOURCE_LIMIT_EXCEEDED]: '资源使用超限',
  [ERROR_CODES.BUSINESS_LOGIC_ERROR]: '业务逻辑错误',
  [ERROR_CODES.OPERATION_NOT_ALLOWED]: '操作不被允许',
  [ERROR_CODES.STATE_CONFLICT]: '状态冲突',
  [ERROR_CODES.DEPENDENCY_ERROR]: '依赖错误',
  [ERROR_CODES.VALIDATION_ERROR]: '验证错误',
  [ERROR_CODES.SYSTEM_ERROR]: '系统错误',
  [ERROR_CODES.DATABASE_ERROR]: '数据库错误',
  [ERROR_CODES.NETWORK_ERROR]: '网络错误',
  [ERROR_CODES.TIMEOUT_ERROR]: '超时错误',
  [ERROR_CODES.CONFIGURATION_ERROR]: '配置错误',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: '外部服务错误',
  [ERROR_CODES.EXTERNAL_SERVICE_UNAVAILABLE]: '外部服务不可用',
  [ERROR_CODES.EXTERNAL_SERVICE_TIMEOUT]: '外部服务超时',
} as const;